### PR TITLE
Create dataset from OpenImages in GUI

### PR DESCRIPTION
**Pull request by GrantPerkins**

### CODE REVIEW

**Comment by GrantPerkins** [comment]
Will probably be angry if you use a class name outside of OpenImages, i.e. `Cats` instead of `Cat`

**Comment by GrantPerkins** [comment]
@AustinShalit the dataset execution now is run through direct python code. no docker shenanigans.

**Review by AustinShalit — COMMENTED** [review]
I tried to create a dataset and it failed with:

```
[1] Create config data created at data/create/9f4e82d0-e8b8-4487-8672-b2214482e47a/data.json
[1] Spawning child process
[1] stdout: Python initialized
[1] ['Remote Control']
[1] Getting dataset, size: 1000, contents: ['Remote Control']
[1]
[1] stderr: Traceback (most recent call last):
[1]   File "/usr/src/app/packages/server/src/assets/openaxon.py", line 161, in <module>
[1]     downloader.download()
[1]   File "/usr/src/app/packages/server/src/assets/openaxon.py", line 50, in download
[1]     download_dataset(dest_dir=self.directory, csv_dir=self.directory, class_labels=self.labels,
[1]   File "/usr/local/lib/python3.9/site-packages/openimages/download.py", line 133, in download_dataset
[1]
[1] stderr:     label_codes = _class_label_codes(class_labels, csv_dir)
[1]
[1] stderr:   File "/usr/local/lib/python3.9/site-packages/openimages/download.py", line 94, in _class_label_codes
[1]     df_classes.loc[df_classes[1] == class_label].values[0][0]
[1] IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by AustinShalit** [comment]
I tried again with a "Person" dataset and it was able to create it. However, it did not create a dataset in the left bar. I had to download the dataset and then reupload the zip file.

**Comment by AustinShalit** [comment]
I'd like to increase the amount of feedback in the UI for downloading images and packing them. Once we merge this, we can open that issue and take care of it later.

Also, when downloading the new dataset, it is just called "dataset.zip". We should name is something better. Maybe "Axon_dataset_list of class names.zip"?

**Comment by GrantPerkins** [comment]
> I tried again with a "Person" dataset and it was able to create it. However, it did not create a dataset in the left bar. I had to download the dataset and then reupload the zip file.

This is currently intentional, as there is no way to download existing datasets.

**Comment by GrantPerkins** [comment]
> I'd like to increase the amount of feedback in the UI for downloading images and packing them. Once we merge this, we can open that issue and take care of it later.
> 
> 
> 
> Also, when downloading the new dataset, it is just called "dataset.zip". We should name is something better. Maybe "Axon_dataset_list of class names.zip"?

I'm a fan of the dataset naming scheme.

**Comment by GrantPerkins** [comment]
> I tried to create a dataset and it failed with:
> 
> 
> 
> ```
> 
> [1] Create config data created at data/create/9f4e82d0-e8b8-4487-8672-b2214482e47a/data.json
> 
> [1] Spawning child process
> 
> [1] stdout: Python initialized
> 
> [1] ['Remote Control']
> 
> [1] Getting dataset, size: 1000, contents: ['Remote Control']
> 
> [1]
> 
> [1] stderr: Traceback (most recent call last):
> 
> [1]   File "/usr/src/app/packages/server/src/assets/openaxon.py", line 161, in <module>
> 
> [1]     downloader.download()
> 
> [1]   File "/usr/src/app/packages/server/src/assets/openaxon.py", line 50, in download
> 
> [1]     download_dataset(dest_dir=self.directory, csv_dir=self.directory, class_labels=self.labels,
> 
> [1]   File "/usr/local/lib/python3.9/site-packages/openimages/download.py", line 133, in download_dataset
> 
> [1]
> 
> [1] stderr:     label_codes = _class_label_codes(class_labels, csv_dir)
> 
> [1]
> 
> [1] stderr:   File "/usr/local/lib/python3.9/site-packages/openimages/download.py", line 94, in _class_label_codes
> 
> [1]     df_classes.loc[df_classes[1] == class_label].values[0][0]
> 
> [1] IndexError: index 0 is out of bounds for axis 0 with size 0
> 
> ```

Does "Remote control" work? Wondering if it's a capitalization thing.

**Comment by AustinShalit** [comment]
> Does "Remote control" work? Wondering if it's a capitalization thing.

It does not.

**Comment by GrantPerkins** [comment]
https://github.com/monocongo/openimages/issues/18 Turns out this is an issue with the API I was using.

**Review by AustinShalit — APPROVED** [review]

**Pull request merged**
