### PR TITLE
fix crash when pausing a stopping trainer

### LINKED ISSUE #172: Axon dies when pausing a stopped container
https://pastebin.com/QuSkvHrc

Ran using `dockerdev`

### PR DESCRIPTION
**Pull request by NLZ432**

### CODE REVIEW

**Review by AustinShalit — COMMENTED** [review]
Do we want to log here instead of silently failing? Could help debug issues in the future

**Comment by NLZ432** [comment]
> Do we want to log here instead of silently failing? Could help debug issues in the future

Good point

**Review by phonymacoroni — CHANGES_REQUESTED** [review]
Issue still exists,

ran using `dockerdev`.

erased docker volume and images
run `dockerdev`
upload dataset
create new project
start training then immediately pressed stop then pause

Screen Shot 2021-02-08 at 11 10 06 AM


log:
https://pastebin.com/986t7LhP

**Review by phonymacoroni — APPROVED** [review]
Issue resolved

**Pull request merged**
