### PR TITLE
Rename artiacts to OS-specific names

### LINKED ISSUE #270: Installer artifact names for releases are unclear
They should be named after the OS they are for. 
image

### PR DESCRIPTION
**Pull request by GrantPerkins**

### CODE REVIEW

**Comment by GrantPerkins** [comment]
I'm not sure how to test this without making a whole release.

**Comment by GrantPerkins** [comment]
image
nevermind.

**Review by AustinShalit — CHANGES_REQUESTED** [review]
Can we try a change like suggested here: https://stackoverflow.com/a/49536006? Updating the action will work but means it is harder to reproduce behavior locally.

**Comment by GrantPerkins** [comment]
Superseded by #283

**Pull request closed without merging**
